version: '3.8'
services:
  mongo:
    image: mongo:7.0.8
    command: [--replSet, rs0, --bind_ip_all, --port, "30001", --quiet, --logpath, /dev/null]
    ports:
      - "30001:30001"
    healthcheck:
      test: test $$(mongosh --port 30001 --quiet --eval "try {rs.initiate({_id:'rs0',members:[{_id:0,host:\"mongo:30001\"}]})} catch(e) {rs.status().ok}") -eq 1
      interval: 10s
      start_period: 30s

  migrations:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_DIR: migrator
    depends_on:
      - mongo
    environment:
      - MONGO_URL=mongodb://mongo:30001

  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_DIR: webserver
    depends_on:
      - migrations
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongo:30001
