version: '3.8'
services:
  mongodb:
    image: mongo:7.0.8
    volumes:
      - mongo-data:/data/db
    ports:
      - "27017:27017"

  migrations:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_DIR: migrator
    depends_on:
      - mongodb
    environment:
      - MONGO_URL=mongodb://mongodb:27017/

  webserver:
    build:
      context: ./
      dockerfile: Dockerfile
      args:
        MAIN_DIR: webserver
    depends_on:
      - migrations
    ports:
      - "8080:8080"
    environment:
      - MONGO_URL=mongodb://mongodb:27017/

volumes:
  mongo-data:
